# This is the config file

# Here you can change keybinds and the program's behaviour

# To make keybind combinations, connect them with +
# Example: shift+f10

# Instead of capital letters, write shift+_
# Example: shift+p

# Instead of ' ', write space
# Example: space

# If an invalid key bind/combination was entered, the program will raise a ValueError.

# Basic keys:
# - ctrl_l - left control
# - shift
# - alt
# - tab
# - f1 (up to f20)
# - home
# - page_up

# Keybinds:
# - record: toggles recording
# - close_program: closes this program
# - play_latest_macro: plays the latest macro, more specifically, 'macros/latest.bmarco'
# - play_selected_macro: plays the below selected macro.
# - stop_macro: stops the marco at any moment

# selected_macro: a path or file name. macro MUST be inside 'macros/'. this is case-sensitive.
# loop (True or False): whether the macro should loop until stopped.


keybinds:
  record: ctrl_l+f1
  close_program: ctrl_l+f2
  play_latest_macro: ctrl_l+f3
  play_selected_macro: ctrl_l+f4
  stop_macro: ctrl+f5

selected_macro: 'macros/mycoolmacro.bmacro'
loop: false

# also this can be written as
# selected_macro: 'mycoolmacro'
# or
# selected_macro: 'mycoolmacro.bmacro'
